version: '2.3'
services:

  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    networks:
      - internal
    environment:
      - POSTGRES_USER=team
      - POSTGRES_PASSWORD=team
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12

networks:
  internal: